scan_filter_chain:
- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 10
    max_angle: 170
    neighbors: 20
    window: 1

- name: intensity
  type: laser_filters/LaserScanIntensityFilter
  params:
    lower_threshold: 10
    upper_threshold: 50
    disp_histogram: 1